site_name: Martin's Tech Blog
site_dir: docs
docs_dir: pages

theme:
  name: mkdocs
  nav_style: dark
  highlightjs: true
  hljs_languages:
    - java
    - typescript
    - ts
    - tsx
  include_homepage_in_sidebar: false
  include_sidebar: false
  features:
    - navigation.tabs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - 'Home': 'index.md'
  - 'Posts':
    - 'Fetching data in React': 'posts/fetching-data-in-react.md'
    - 'Styled Components with React': 'posts/styled-components-with-react.md'
  - 'Advent of Code 2022':
    - 'Day 1 - Counting Calories': 'advent-of-code-2022/day-01.md'